// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: journal_entries.sql

package database

import (
	"context"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (title, content, user_id)
VALUES (?, ?, ?)
RETURNING id, title, content, created_at, updated_at, user_id
`

type CreateJournalEntryParams struct {
	Title   string
	Content string
	UserID  int64
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, createJournalEntry, arg.Title, arg.Content, arg.UserID)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
