// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type JournalEntry struct {
	ID        int64
	Title     string
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    int64
}

type Project struct {
	ID          int64
	Title       string
	Description string
	ImageUrl    sql.NullString
	Link        sql.NullString
	Github      sql.NullString
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	UserID      int64
}

type ProjectTag struct {
	ProjectID int64
	TagID     int64
}

type RefreshToken struct {
	ID        int64
	Token     string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt time.Time
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
}

type User struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Name      string
	Password  string
	Bio       sql.NullString
	Email     sql.NullString
	Github    sql.NullString
	Linkedin  sql.NullString
}
