// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type JournalEntry struct {
	ID        int64
	Title     string
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    int64
}

type RefreshToken struct {
	ID        int64
	Token     string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt time.Time
}

type User struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Name      string
	Password  string
}
