// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type JournalEntry struct {
	ID        int64
	Title     string
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    int64
}

type User struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Name      string
	ApiKey    string
}
