// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package database

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (title, description, image_url, link, github, status, user_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, description, image_url, link, github, status, created_at, updated_at, user_id
`

type CreateProjectParams struct {
	Title       string
	Description string
	ImageUrl    sql.NullString
	Link        sql.NullString
	Github      sql.NullString
	Status      sql.NullString
	UserID      int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.Link,
		arg.Github,
		arg.Status,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Link,
		&i.Github,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
