-- +goose Up
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL DEFAULT 'unset'
);

-- +goose Down
DROP TABLE users;