-- +goose Up
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  api_key TEXT UNIQUE NOT NULL
);

-- +goose Down
DROP TABLE users;